from setuptools import setup

setup(
    name="opentelemetry-ext-newrelic",
    use_scm_version={
        "write_to": "src/opentelemetry_ext_newrelic/version.py",
        "write_to_template": """\
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = "{version!s}"
""",
    },
    install_requires=("opentelemetry-sdk>=0.15b0", "newrelic-telemetry-sdk>=0.4.0,<0.5"),
)
